### ISSUE TITLE
error when run with docker-compose on my mac 

### ISSUE THREAD

**Issue by skanel** [ottofeller/rxdb-graphql-replication-ssr#1]
kanel@MacBooker ERP-web % docker-compose up                  
Traceback (most recent call last):
  File "/usr/local/Cellar/docker-compose/1.29.1/libexec/lib/python3.9/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/usr/local/Cellar/docker-compose/1.29.1/libexec/lib/python3.9/site-packages/urllib3/connectionpool.py", line 394, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/local/Cellar/python@3.9/3.9.4/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 1253, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/local/Cellar/python@3.9/3.9.4/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 1299, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/local/Cellar/python@3.9/3.9.4/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 1248, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/local/Cellar/python@3.9/3.9.4/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 1008, in _send_output
    self.send(msg)
  File "/usr/local/Cellar/python@3.9/3.9.4/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 948, in send
    self.connect()
  File "/usr/local/Cellar/docker-compose/1.29.1/libexec/lib/python3.9/site-packages/docker/transport/unixconn.py", line 43, in connect
    sock.connect(self.unix_socket)
FileNotFoundError: [Errno 2] No such file or directory

During handling of the above exception, another exception occurred:

**Comment by gvidon** [comment]
@skanel is the Docker server running? Are you on Silicon Mac?

**Comment by skanel** [comment]
i am on this mac.


`Software:

    System Software Overview:

      System Version: macOS 11.2.3 (20D91)
      Kernel Version: Darwin 20.3.0
      Boot Volume: Macintosh HD
      Boot Mode: Normal
      Computer Name: MacBooker
      Secure Virtual Memory: Enabled
      System Integrity Protection: Enabled
      Time since boot: 7 minutes`
